# BudgetKu - GitHub Pages Configuration
title: "BudgetKu - Smart Finance Manager"
description: "Aplikasi manajemen keuangan modern dengan analisis prediktif dan UI yang elegan"
url: "https://erzambayu.github.io"
baseurl: "/BudgetKu"

# Disable Jekyll processing for static HTML app
plugins: []
markdown: kramdown
highlighter: rouge

# Include files
include:
  - ".nojekyll"

# Exclude unnecessary files
exclude:
  - "README.md"
  - "LICENSE" 